services:
  k6:
    image: grafana/k6:latest
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    command: run /scripts/test.js
    volumes:
      - ./scripts:/scripts
      - ./results:/results

  web-server:
    image: nginx:latest
    ports:
      - "8069:80"
    volumes:
      - ./results:/usr/share/nginx/html:ro